version: 2

build:
  commands:
    - echo "Building Pet Paradise Backend..."
    - mvn clean package -DskipTests

deploy:
  - echo "Starting Pet Paradise Backend..."
  - java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar target/pet-paradise-backend-0.0.1-SNAPSHOT.jar
