services:
  - type: web
    name: petparadise-backend
    env: java
    buildCommand: |
      if command -v mvn > /dev/null; then
        mvn clean package -DskipTests
      else
        chmod +x ./mvnw
        ./mvnw clean package -DskipTests
      fi
    startCommand: java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar target/pet-paradise-backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JWT_SECRET
        value: mySecretKey1234567890123456789012345678901234567890
      - key: CORS_ORIGINS
        value: http://localhost:5173,http://localhost:5174
